services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medtrack-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medtrack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  appwrite-uploads:
  appwrite-cache:
  appwrite-config:
  appwrite-db:
  appwrite-redis-data:
